// AUTH
export const FETCH_AUTH = 'FETCH_AUTH'
export const RECEIVE_AUTH = 'RECEIVE_AUTH'
export const FAILED_AUTH = 'FAILED_AUTH'
export const FETCH_LOGOUT_USER = 'FETCH_LOGOUT_USER'

// ACCOUNT UPDATE
export const FETCH_CHANGE_ACCOUNT = 'FETCH_CHANGE_ACCOUNT'
export const RECEIVE_CHANGE_ACCOUNT = 'RECEIVE_CHANGE_ACCOUNT'
export const FAILED_CHANGE_ACCOUNT = 'FAILED_CHANGE_ACCOUNT'

// FORGOT PASSWORD
export const FETCH_FORGOT_PASSWORD = 'FETCH_FORGOT_PASSWORD'
export const RECEIVE_ITEM_FORGOT_PASSWORD = 'RECEIVE_ITEM_FORGOT_PASSWORD'
export const FAILED_FORGOT_PASSWORD = 'FAILED_FORGOT_PASSWORD'

// IMAGE
export const FETCH_IMAGE = 'FETCH_IMAGE'
export const SUCCESS_IMAGE = 'SUCCESS_IMAGE'
export const FAILED_IMAGE = 'FAILED_IMAGE'

// CURRENT TIME
export const FETCH_CURRENT_TIME = 'FETCH_CURRENT_TIME'
export const FAILED_CURRENT_TIME = 'FAILED_CURRENT_TIME'
export const RECEIVE_CURRENT_TIME = 'RECEIVE_CURRENT_TIME'

// FOOD COURT
export const FETCH_FOODCOURT = 'FETCH_FOODCOURT'
export const FAILED_FOODCOURT = 'FAILED_FOODCOURT'
export const RECEIVE_FOODCOURT = 'RECEIVE_FOODCOURT'
export const RECEIVE_ITEM_FOODCOURT = 'RECEIVE_ITEM_FOODCOURT'

// STAND
export const FETCH_STAND = 'FETCH_STAND'
export const FAILED_STAND = 'FAILED_STAND'
export const RECEIVE_STAND = 'RECEIVE_STAND'
export const RECEIVE_ITEM_STAND = 'RECEIVE_ITEM_STAND'

// CATEGORY_STAND
export const FETCH_CATEGORY_STAND = 'FETCH_CATEGORY_STAND'
export const FAILED_CATEGORY_STAND = 'FAILED_CATEGORY_STAND'
export const RECEIVE_CATEGORY_STAND = 'RECEIVE_CATEGORY_STAND'
export const RECEIVE_ITEM_CATEGORY_STAND = 'RECEIVE_ITEM_CATEGORY_STAND'

// HOME_STAND
export const FETCH_HOME_STAND = 'FETCH_HOME_STAND'
export const FAILED_HOME_STAND = 'FAILED_HOME_STAND'
export const RECEIVE_HOME_STAND = 'RECEIVE_HOME_STAND'
export const RECEIVE_ITEM_HOME_STAND = 'RECEIVE_ITEM_HOME_STAND'

// PRODUCT
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const FAILED_PRODUCT = 'FAILED_PRODUCT'
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT'
export const RECEIVE_ITEM_PRODUCT = 'RECEIVE_ITEM_PRODUCT'

// USER
export const FETCH_USER = 'FETCH_USER'
export const FAILED_USER = 'FAILED_USER'
export const RECEIVE_USER = 'RECEIVE_USER'
export const RECEIVE_ITEM_USER = 'RECEIVE_ITEM_USER'

// TABLE SESSION
export const FETCH_SESSION_TABLE = 'FETCH_SESSION_TABLE'
export const FAILED_SESSION_TABLE = 'FAILED_SESSION_TABLE'
export const RECEIVE_ITEM_SESSION_TABLE = 'RECEIVE_ITEM_SESSION_TABLE'

// VERIFICATION
export const FETCH_VERIFICATION = 'FETCH_VERIFICATION'
export const SUCCESS_VERIFICATION = 'SUCCESS_VERIFICATION'
export const FAILED_VERIFICATION = 'FAILED_VERIFICATION'

// RESET PASSWORD
export const FETCH_RESET_PASSWORD = 'FETCH_RESET_PASSWORD'
export const SUCCESS_RESET_PASSWORD = 'SUCCESS_RESET_PASSWORD'
export const FAILED_RESET_PASSWORD = 'FAILED_RESET_PASSWORD'

// GENERATED TYPES
